name: Django CI

on:
  push:
    branches:
    - 'develop'
  pull_request:
    branches:
    - 'develop'

jobs:
  build-docker-dev:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Build Docker image (dev)
        run: docker-compose -f docker-compose.yml build

  build-docker-prod:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Build Docker image (prod)
        run: docker-compose -f docker-compose.yml -f docker-compose.prod.yml build
